version: '3'
services:
    influxdb:
        image: 'influxdb:latest'
        ports:
            - 8086:8086
        environment:
            - INFLUXDB_ADMIN_USER=admin
            - INFLUXDB_ADMIN_PASSWORD=admin

    garie-plugin:
        build: .
        privileged: true
        volumes:
#            - ../garie-plugin:/garie-plugin
            - .:/app
            - /var/run/docker.sock:/run/docker.sock
            - /usr/bin/docker:/bin/docker
        environment:
            - HOST=influxdb
        depends_on:
            - influxdb
        command: bash -c "tail -f /dev/null"

    chronograf:
        image: 'chronograf:latest'
        ports:
            - 8888:8888
        depends_on:
            - influxdb
